micronaut:
  application:
    name: expenses
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
datasources:
  default:
#    url: jdbc:h2:mem:devDb
#    username: sa
#    password: ''
#    schema-generate: CREATE_DROP
#    driver-class-name: org.h2.Driver
#    dialect: H2
    db-type: mysql
    url: jdbc:mariadb://localhost:3306/db
    username: root
    password: root
    schema-generate: CREATE_DROP
    driver-class-name: org.mariadb.jdbc.Driver
    dialect: MariaDB
jpa:
  default:
    entity-scan:
      packages:
        - 'me.jvegaf.user.domain'
        - 'me.jvegaf.group.domain'
        - 'me.jvegaf.expense.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true